### ISSUE TITLE
Allow to copy from console

### ISSUE THREAD

**Issue by kooba** [DawidMyslak/kubernetes-helm-ui#1]
Not sure how hard would it be, but it would be nice to be able to copy from the console window.

**Comment by DawidMyslak** [comment]
Thanks @kooba, yeah should be easy enough, I will try add this feature soon 👍 .

**Comment by DawidMyslak** [comment]
Hey @kooba, this should do the job: https://github.com/DawidMyslak/kubernetes-helm-ui/pull/3

New version 1.0.1 released, links in README.
