### ISSUE TITLE
Produces an error with local context

### ISSUE THREAD

**Issue by andreyshamray** [DawidMyslak/kubernetes-helm-ui#6]
It is not working for me, application produces an error --kube-context
➜ /usr/local/bin/helm list --kube-context "local" --tiller-namespace "default"
Error: could not find tiller

![image](https://user-images.githubusercontent.com/32450129/40123379-c73e88c8-592e-11e8-84e6-f670e89c6ea6.png)

I am using dmg version. And context option is not available to change. 
![image](https://user-images.githubusercontent.com/32450129/40123573-2feff4ec-592f-11e8-95dd-99a9ac5326f2.png)

Could you help with it?

**Comment by DawidMyslak** [comment]
Hey @andreyshamray 👋 

What commands do you use to work with `helm` in your terminal? Is `helm list` working from there?

**Comment by andreyshamray** [comment]
Hi yes from the console it is working fine.
12:43:00~$ helm ls
NAME             	REVISION	UPDATED                 	STATUS  	CHART                     	NAMESPACE  
dashboard-v1     	1       	Wed May 16 14:33:26 2018	DEPLOYED	kubernetes-dashboard-0.6.8	kube-system
heapster-v1      	1       	Wed May 16 14:32:39 2018	DEPLOYED	heapster-0.2.10           	kube-system
nginx-v1         	1       	Wed May 16 14:35:21 2018	DEPLOYED	nginx-ingress-0.9.3       	default

**Comment by DawidMyslak** [comment]
Could you run this and paste the result here?
```
kubectl get namespaces --context="local"
```
Is the "default" on the list?

**Comment by andreyshamray** [comment]
Yes it is:
12:43:05~$ kubectl get namespaces --context="local"
NAME          STATUS    AGE
default       Active    1d
kube-public   Active    1d
kube-system   Active    1d

**Comment by DawidMyslak** [comment]
@andreyshamray I wish I could be more helpful, but really have no clue what's wrong there 😞.

**Comment by janosroden** [comment]
@andreyshamray are you sure tiller is in the 'default' namespace? Usually it's in 'kube-system'.

**Comment by andreyshamray** [comment]
Oh yep, I have changed Namespace to kube-system, and now it working. Thanks a lot! 
![image](https://user-images.githubusercontent.com/32450129/40225576-0ee68572-5a92-11e8-9bdf-88d721b6b5ad.png)

**Comment by DawidMyslak** [comment]
Awesome, nice one!
