### ISSUE TITLE
could not find tiller

### ISSUE THREAD

**Issue by tomislater** [DawidMyslak/kubernetes-helm-ui#7]
An output from console:
```
➜ /usr/local/bin/kubectl get namespaces --context="ci"
```
It works, I have got info about namespaces, but this guy:

```
➜ /usr/local/bin/helm list --kube-context "ci" --tiller-namespace "my-namespace"
Error: could not find tiller
```
does not work. I have changed `src/renderer/tools/helm.js` file. I have changed `getReleases` function. Use `--namespace` instead of `--tiller-namespace`, and it works, but I do not think it is a proper solution.

**Comment by DawidMyslak** [comment]
Hey @tomislater !

Check official docs for `helm list` command: https://docs.helm.sh/helm/#helm-list
```
--namespace string                show releases within a specific namespace
--tiller-namespace string         namespace of Tiller (default "kube-system")
```

Are you sure that tiller "my-namespace" runs on your Kubernetes cluster?

**Comment by tomislater** [comment]
> Are you sure that tiller "my-namespace" runs on your Kubernetes cluster?

Ugh, it runs in `kube-system` namespace. According to [this file](https://github.com/DawidMyslak/kubernetes-helm-ui/blob/master/src/renderer/tools/helm.js), we assume that tiller is deployed in every namespace, right? Ok, so now I see where is the problem :P.
