### ISSUE TITLE
packing as helm chart

### ISSUE THREAD

**Issue by obeyler** [DawidMyslak/kubernetes-helm-ui#8]
Hello Dawid,
Why don't you provide kubernetes-helm-ui as also an Helm chart ?
Best regards
Olivier

**Comment by DawidMyslak** [comment]
Hey Olivier, thanks for your feedback!

The app I have created is a desktop app. I’m not sure what’s the purpose of providing it as a Helm chart?

**Comment by obeyler** [comment]
Ok If it's a desktop app there is no interest to pack as helm chart.
I was looking for this kind of application as a web server. I've found what I was looking for in an other project monocular. They also show what helm chart are deployed on the kubernetes server.
Best regards
